### ISSUE TITLE
Is there any way to create half circle? 

### ISSUE THREAD

**Issue by babulpatel1309** [davidanaya/flutter-circular-slider#8]
I want to make a design like speedOmeter with the handle and same dragging event like yours. Can you please help me to build that? Or suggest the way to build half circle?

**Comment by davidanaya** [comment]
Hi @babulpatel1309 I have no plans to build that but it should be fairly similar to what I just did. Feel free to fork the repo and do your own version, basically you will need to rewrite the `painter` class which is the one doing the drawing in Flutter canvas, but build half a circle instead of the whole one.
